version: '3'

#networks:
#  app:
#    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - ${APP_PORT:-80}:80

#  mysql:
#    image: 'mysql:8.0'
#    environment:
#      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_DATABASE: '${DB_DATABASE}'
#      MYSQL_USER: '${DB_USERNAME}'
#      MYSQL_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#    networks:
#      - app
#    ports:
#      - '${FORWARD_MYSQL_PORT:-3306}:3306'
